### PR TITLE
Changed 'on_crash' value to 'destroy' as specified in xl.cfg manpage.

### PR DESCRIPTION
**Pull request by diederikdehaas**
This would fix https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853083

### CODE REVIEW

**Comment by xtaran** [comment]
Hi Diederik,

Diederik de Haas wrote:
> According to man:/xl.cfg the default action of 'on_crash' is 'destroy',
> but /etc/xen-tools/xm.tmpl contains:
> on_crash    = 'restart'

Yes, at that point xen-tools' defaults are different than Xen's. But
is that a bug? Even if xen-tools does it deliberately?

But I must admit, I'm unsure if I should really change xen-tools'
default here. I do see that not following Xen's default values might
break some users' expectations, but I consider the automatic reboot on
crash rather a feature than a bug. I see that setting like a watchdog.

Of course, if I start a DomU and it crashes immediately and over and
over again, I should fix that. But I should anyways check if a freshly
started DomU actually works. (And I consider crashing later and then
getting into a endless boot loop to be rather seldom, maybe happening
with rolling-release-style distributions.)

Additionally, if I want to not deviate from Xen's defaults I'd rather
remove that value completely. Because what that line does is
overwriting Xen's default. If I overwrite the default value with the
default value I ask for future deviation from a potentially changing
default value. So while I do see the problem, I don't consider your
submitted patch to be suitable as a fix.

Another potential way to fix this bug report is IMHO to make clear
in the documentation that xen-tools' defaults deviate from Xen's
defaults.

		Regards, Axel
-- 
 ,''`.  |  Axel Beckert <abe@debian.org>, http://people.debian.org/~abe/
: :' :  |  Debian Developer, ftp.ch.debian.org Admin
`. `'   |  4096R: 2517 B724 C5F6 CA99 5329  6E61 2FF9 CD59 6126 16B5
  `-    |  1024D: F067 EA27 26B9 C3FC 1486  202E C09E 1D89 9593 0EDE

**Comment by xtaran** [comment]
As mentioned in my mail: While the issue is debatable, a fix should not overwrite a default with the same value if deviating from the default is the issue. Hence closing the pull request.

Feel free to either open an issue for this or to push a commit which just removes the line in question instead. (In the later case I'd reopen the puil request for further discussion.)

**Comment by diederikdehaas** [comment]
Valid point and I agree it's debatable.

But along those same lines, shouldn't `on_poweroff` and `on_reboot` be removed as they *do* have the default value?

**Comment by xtaran** [comment]
Control: clone -1 -2
Control: retitle -2 xen-tools: xm.tmpl overwrites Xen's default values with the same values
Control: severity -2 minor
Control: notforwarded -2

Hi Diederik,

On Sun, Jan 29, 2017 at 03:21:29PM -0800, Diederik de Haas wrote:
> But along those same lines, shouldn't `on_poweroff` and `on_reboot`
> be removed as they *do* have the default value?

That's a very valid point. :-) I cloned your initial Debian bug report
into an additional one with this mail.

One thing I should also verify before implementing a fix (to both bug
reports btw.) is if both, "xm create" and "xl create", actually work
fine if none of these parameters is set. (I do expect so, but I want
to have that confirmed.)

		Kind regards, Axel
-- 
/~\  Plain Text Ribbon Campaign                   | Axel Beckert
\ /  Say No to HTML in E-Mail and News            | abe@deuxchevaux.org  (Mail)
 X   See http://www.nonhtmlmail.org/campaign.html | abe@noone.org (Mail+Jabber)
/ \  I love long mails: http://email.is-not-s.ms/ | http://abe.noone.org/ (Web)

**Pull request closed without merging**
