### PR TITLE
Eliminate progress reporting which is useless in logs

### PR DESCRIPTION
**Pull request by YSakhno**
Hello,

I've made this little change that sanitizes logs a little by filtering out information about progress during software/packages install. Without it logs are full of (Reading database ... 5%^M(Reading database ... 10%^M and so on stuff.

Yuri Sakhno.

### CODE REVIEW

**Comment by xtaran** [comment]
Hrm, while I do see that progress reporting doesn't make sense in log files I strongly dislike the idea of having "quiet" logs. First need to check how quiet `--quiet` is.

**Comment by YSakhno** [comment]
Actually, I cannot see the difference with and without `--quiet` (did not check very thoroughly though).

And `--quiet` (of any level) is not enough to silence the 'Reading database' messages because those do not come from apt-get according to this: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/874409

**Comment by xtaran** [comment]
I just went through dpkg's options and found non to silence it. The only one which might help here is `--status-fd`.

**Comment by YSakhno** [comment]
Well, yes. That's why the need for sed-filtering. If you are not comfortable with `--quiet` option, you may omit it, I am fine with that (since it seems to make no real difference whatsoever). Just be sure to keep sed-filtering in place.

**Pull request merged**
